_target_: model.regressive.RegressiveMLP

# Choose between full (BMBO-DARN) or seq (DNN-MFBO) implementation
regressive_mode: "full"
base_num_hidden: 64
base_num_layer: 2
fid_num_hidden: 64
feature_dim: ${model.fid_num_hidden} #required to set number of features in mf-svgp
activation: "relu"
dropout_base: 0.0
dropout_fid: 0.0
num_output: 1
