_target_: src.model.regressor.DropoutRegressor

# Device
device: cuda

# Path
path_model: "./storage/model_proxy/proxy"

# Training
training:
  eps : 1.0e-4
  dropout : 0.1
  max_epochs : 300
  training_batch : 8
  history : 50