_target_: model.multi_fidelity_mlp.MultiFidelityMLP

# if False, each fidelity has a separate fully connected module
shared_head: True
base_num_hidden: 512
base_num_layer: 2
fid_num_hidden: 512
fid_num_layer: 2
activation: "relu"
dropout_prob: 0.1
num_output: 1
