root_logdir: "/network/scratch/h/hernanga/mfal"
plot:
    dpi: 150
    height: 6
    width: 10
    dodge: 0.6
    scale: 0.75
    errwidth: 1.5
    bs_n: 1000
    bs_seed: 17
    plot_baseline: False
    shade_alpha: 0.10
    estimator: mean
    do_markers: False
    markers:
        - "o"
        - "s"
        - "X"
        - "d"
        - "o"
        - "o"
    colors:
        mf:
            palette: colorblind
            index: 0
        mf_index:
            palette: colorblind
            index: 0
        mf_linear:
            palette: colorblind
            index: 1
        mf_random:
            palette: colorblind
            index: 2
        mf_random_fid:
            palette: colorblind
            index: 3
        sf:
            palette: colorblind
            index: 4
        ppo:
            palette: colorblind
            index: 5
    x_axis:
        log: True
        type: "fraction_budget"
        label: "Fraction of total budget"
    do_all_k: False
    do_line_top1: True
    linewidth:
        highlight: 3
        other: 2
