root_logdir: "/network/scratch/h/hernanga/mfal"
plot:
    dpi: 150
    height: 6
    width: 10
    dodge: 0.6
    scale: 0.75
    errwidth: 1.5
    bs_n: 1000
    bs_seed: 17
    plot_baseline: False
    shade_alpha: 0.10
    estimator: mean
    do_markers: False
    markers:
        - "o"
        - "s"
        - "X"
        - "d"
        - "o"
        - "o"
    colors:
        hue:
            palette: mako
        models:
            palette: vlag
        methods_family:
            palette: deep
    x_axis:
        log: True
        type: "fraction_budget"
        label: "Fraction of total budget"
