root_logdir: "/network/scratch/h/hernanga/mfal"
plot:
    dpi: 150
    height: 6
    width: 10
    dodge: 0.6
    scale: 0.75
    errwidth: 1.5
    bs_n: 1000
    bs_seed: 17
    plot_baseline: False
    shade_alpha: 0.10
    estimator: mean
    do_markers: False
    markers:
        - "o"
        - "s"
        - "X"
        - "d"
        - "o"
        - "o"
    methods:
        mfgfn:
            palette: colorblind
            palette_idx: 0
            name: "MF-GFlowNet"
        mfgfn_linear:
            palette: colorblind
            palette_idx: 0
            name: "MF-GFlowNet (GP Linear)"
        mfgfn_index:
            palette: colorblind
            palette_idx: 9
            name: "MF-GFlowNet (GP Index)"
        mf_random:
            palette: colorblind
            palette_idx: 3
            name: "Random"
        random_fid_gfn:
            palette: colorblind
            palette_idx: 1
            name: "Random fidelities GFlowNet"
        sfgfn:
            palette: colorblind
            palette_idx: 2
            name: "SF-GFlowNet"
        mfppo:
            palette: colorblind
            palette_idx: 4
            name: "MF-PPO"
    x_axis:
        log: True
        type: "fraction_budget"
        label: "Fraction of total budget"
    do_all_k: False
    do_line_top1: True
    linewidth:
        highlight: 3
        other: 2
