root_logdir: "/network/scratch/h/hernanga/mfal"
plot:
    dpi: 150
    height: 6
    width: 10
    dodge: 0.6
    scale: 0.75
    errwidth: 1.5
    bs_n: 1000
    bs_seed: 17
    plot_baseline: False
    shade_alpha: 0.10
    estimator: mean
    do_markers: False
    markers:
        - "o"
        - "s"
        - "X"
        - "d"
        - "o"
        - "o"
    methods:
        mfgfn:
            palette: colorblind
            palette_idx: 0
            name: "MF-GFlowNet"
            dash: solid
            linewidth: 3
        mfgfn_linear:
            palette: colorblind
            palette_idx: 0
            name: "MF-GFlowNet (GP Linear)"
            dash: solid
            linewidth: 3
        mfgfn_index:
            palette: colorblind
            palette_idx: 9
            name: "MF-GFlowNet (GP Index)"
            dash: solid
            linewidth: 3
        mf_random:
            palette: colorblind
            palette_idx: 4
            name: "Random"
            dash: loosely dashed
            linewidth: 2
        random_fid_gfn:
            palette: colorblind
            palette_idx: 1
            name: "Rand. fid. GFN"
            dash: dashed
            linewidth: 2
        sfgfn:
            palette: colorblind
            palette_idx: 2
            name: "SF-GFlowNet"
            dash: dotted
            linewidth: 2
        mfppo:
            palette: tab10
            palette_idx: 5
            name: "MF-PPO"
            dash: loosely dotted
            linewidth: 2
    x_axis:
        log: True
        type: "fraction_budget"
        label: "Fraction of total ${plot.methods.sfgfn.name} budget"
    do_all_k: False
    do_line_top1: False
    linewidth:
        highlight: 2
        other: 1
