_target_: regressor.dkl.DeepKernelRegressor

checkpoint: proxy
optim: adam

surrogate:
  _target_: model.gp_models.SingleTaskMultiFidelityLikeBotorchSVGP
  max_shift: 0
  mask_size: 0
  bootstrap_ratio: null
  min_num_train: 128
  task_noise_init: 0.5
  lengthscale_init: 0.7
  gp_lr: 1e-3
  enc_lr: 1e-3
  bs: ${dataset.dataloader.train.batch_size}
  eval_bs: ${dataset.dataloader.test.batch_size}
  num_epochs: 512
  holdout_ratio: 0.1 #0.2
  early_stopping: True
  patience: 32
  eval_period: 5
  feature_dim: ${model.feature_dim}
  out_dim: 1
  num_inducing_points: 64
  learn_inducing_points: True
  encoder_wd: 1e-4
  mll_beta: 1e-2
  lengthscale_prior:
    _target_: gpytorch.priors.NormalPrior
    loc: ${regressor.surrogate.lengthscale_init}
    scale: 1e-2
  noise_constraint:
    _target_: gpytorch.constraints.GreaterThan
    lower_bound: 1e-4