debug: 1
gflownet:
  env_id: aptamers
  adam_beta1: 0.9
  adam_beta2: 0.999
  batch_reward: 1
  bootstrap_tau: 0.0
  ckpt_period: 100
  clip_grad_norm: 0.0
  comet:
    project: aptamers-gflownet
    skip: 0
    tags:
      - potts
      - len30
  device: cuda
  early_stopping: 0.0
  func: potts new
  learning_rate: 0.001
  loss: tb
  lr_z_mult: 100
  max_seq_length: 30
  max_word_len: 1
  mbsize: 16
  min_seq_length: 30
  min_word_len: 1
  model_ckpt: gfn.pt
  momentum: 0.9
  n_hid: 512
  n_iter: 20000
  n_layers: 3
  nalphabet: 4
  num_empirical_loss: 200000
  opt: adam
  pct_batch_empirical: 0.0
  progress: 1
  temperature_logits: 1.0
  reward_norm_std_mult: 8
  reward_beta: 0.5
  reward_func: boltzmann
  train:
    n: 1000
    seed: 168
  test:
    path: /network/scratch/a/alex.hernandez-garcia/datasets/potts/test_pottsenergy_n10000_len30_seed167.csv
    period: 100
    score: energies
  oracle:
    nsamples: 1000
    period: 500
    k:
      - 1
      - 10
      - 100
  train_to_sample_ratio: 1
