defaults:
  - base

_target_: gflownet.envs.grid.Grid

id: grid
func: corners
# Dimensions of hypergrid
n_dim: 2
# Number of cells per dimension
length: 10     # <---
# Maximum increment per each dimension that can be done by one action
max_increment: 1
# Maximum number of dimensions that can be incremented by one action
max_dim_per_action: 1
# Mapping coordinates
cell_min: 0     # <---
cell_max: 0.9  # <---
# Buffer
buffer:
  train: null
  test: null
