
_target_: gflownet.utils.logger.Logger

do:
  online: False # <---
  times: False

project_name: "test_gflownet" # <---

# Log dir
logdir:
  root: activelearning/gflownet/logs
  ckpts: activelearning/gflownetckpts
  overwrite: True
debug: False
lightweight: False
progress: True
context: "0"
notes: null # wandb run notes (e.g. "baseline")
tags: 
    - gflownet