defaults:
  - crystal_surface
  - atomgraphconverter: pyxtal_converter

has_crystal_to_miller_constraints: True
crystal_kwargs:
  do_sg_before_composition: True
  do_sg_to_lp_constraints: True
  do_sg_to_composition_constraints: True
  do_composition_to_sg_constraints: False
  composition_kwargs:
    elements: [1, 3, 5, 6, 7, 8, 9, 11, 12, 13, 14, 15, 16, 17, 19, 23, 25, 26, 27, 28, 29, 34]
    max_diff_elem: 5
    min_diff_elem: 1
    min_atoms: 1
    max_atoms: 80
    min_atom_i: 1
    max_atom_i: 16
    do_charge_check: True
  space_group_kwargs:
    space_groups_subset: [16, 18, 19, 20, 21, 25, 26, 29, 30, 31, 33, 36, 38, 40, 41, 43, 44, 46, 47, 51, 52, 53, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 69, 70, 71, 72, 74, 82, 84, 85, 86, 87, 88, 92, 99, 102, 107, 113, 114, 121, 122, 123, 126, 129, 131, 136, 137, 138, 139, 140, 141, 198, 199, 205, 206, 216, 217, 220, 221, 224, 225, 227, 229, 230]
  lattice_parameters_kwargs:
    min_length: 0.9
    max_length: 100.0
    min_angle: 50.0
    max_angle: 150.0
    n_comp: 5
    beta_params_min: 0.1
    beta_params_max: 100.0
    min_incr: 0.1
    fixed_distr_params:
      beta_weights: 1.0
      beta_alpha: 10.0
      beta_beta: 10.0
      bernoulli_eos_prob: 0.1
      bernoulli_bts_prob: 0.1
    random_distr_params:
      beta_weights: 1.0
      beta_alpha: 10.0
      beta_beta: 10.0
      bernoulli_eos_prob: 0.1
      bernoulli_bts_prob: 0.1
miller_kwargs:
  is_hexagonal_rhombohedral: False
  max_increment: 1
  max_dim_per_action: 1
reward_func: identity
reward_beta: 1
buffer:
  replay_capacity: 10
  train: null
  test: null