# @package _global_

defaults:
  # - _self_
  - env: amp
  - oracle: amp
  - gflownet: trajectorybalance
  - user: nikita
  - proxy: dropout_regressor
  - dataset: dataset
  - regressor: dropout_regressor
  - model: mlp
  - logger: wandb

logger:
  project_name: "Scratch"
  test:
    period: 1
  oracle:
    period: 1000
  do:
    times: False
    online: False
  tags:
    - e^(10x)
    - amp
    - tb
    - mcd
    - partition=150
    - no_offline
    - backward_policy = shared
    - sampling_temp=1.0
    # - lr=1e-3

env:
  reward_func: boltzmann
  reward_beta: 10.0
  # reward_norm: 0.1
  buffer:
    train:
      path: null
      # /home/mila/n/nikita.saxena/activelearning/storage/amp/data_train.csv
      n: null
      seed: null
      output_csv: null 
    test:
    # /home/mila/n/nikita.saxena/activelearning/storage/amp/
      path: data_test.csv
      n: null
      seed: null
      output_csv: null 
    

gflownet:
  sample_only: False
  random_action_prob: 0.001
  optimizer:
    lr: 5e-4
    lr_z_mult: 20
    n_train_steps: 30000
    batch_size: 32
  policy:
    forward:
      type: mlp
      n_hid: 2048
      n_layers: 2
    backward:
      type: mlp
      shared_weights: True
  pct_batch_empirical: 0.0
  oracle:
    n: 500

model:
  n_hid: 2048
  n_layers: 2

regressor:
  weight_decay: 1e-4
  lr: 1e-4
  max_epochs: 100
  history: 5

dataset:
  # split: random
  dataloader:
    train:
      batch_size: 256
    test:
      batch_size: 256
  path:
    oracle_dataset:
      train: /home/mila/n/nikita.saxena/activelearning/storage/amp/data_train.csv
      test: /home/mila/n/nikita.saxena/activelearning/storage/amp/data_test.csv
  
# Number of objects to sample at the end of training
# Sample 5*K and choose topK
n_samples: 4 #1024
# Random seeds
seed: 0
# Device
device: cuda
# Float precision
float_precision: 32
al_n_rounds: 1


# Hydra config
hydra:
  # See: https://hydra.cc/docs/configure_hydra/workdir/
  run:
    dir: ${user.logdir.root}/${now:%Y-%m-%d_%H-%M-%S}
  job:
    # See: https://hydra.cc/docs/upgrades/1.1_to_1.2/changes_to_job_working_dir/
    # See: https://hydra.cc/docs/tutorials/basic/running_your_app/working_directory/#disable-changing-current-working-dir-to-jobs-output-dir
    chdir: True