device: "cpu"
gflownet:
  progress: True
  model_ckpt: !!null
  learning_rate: 0.0001
  opt: "adam"
  adam_beta1: 0.9
  adam_beta2: 0.999
  momentum: 0.9
  mbsize: 10
  train_to_sample_ratio: 1
  n_hid: 256
  n_layers: 2
  n_iter: 1000
  num_empirical_loss: 200000
  clip_grad_norm: 0.0
  func: "linear"
  horizon: 10
  nalphabet: 4
  bootstrap_tau: 0.0
  batch_reward: False
  comet: 
    project: !!null
    tags: []
