defaults:
  - env: grid
  - gflownet: gflownet
  - proxy: dropout_regressor
  - oracle: grid_corners
  - dataset: dataset
  - model: dropout_regressor
  - network: mlp
  - logger: wandb

n_samples: 100
al_n_rounds: 10
log:
  skip: False 
  tags: 
    - dummy1
    - dummy2