defaults:
  - env: grid
  - gflownet: gflownet
  - proxy: dropout_regressor
  - oracle: grid_corners
  - dataset: dataset
  - regressor: dropout_regressor
  - model: mlp

n_samples: 100
al_n_rounds: 10