defaults:
  - env: grid
  - gflownet: gflownet
  - proxy: dropout_regressor
  - oracle: grid_corners
  - dataset: dataset
  - regressor: dropout_regressor
  # Choose from mf_mlp, regressive, for MF and mlp, transfromer for SF
  - model: regressive

n_samples: 100
al_n_rounds: 10