defaults:
  - _self_
  - env: grid
  - gflownet: gflownet
  - proxy: dropout_regressor
  # TODO: change to grid once continuous is merged
  - oracle@_oracle_dict.1: grid_corners
  - oracle@_oracle_dict.2: grid_corners
  - dataset: dataset
  - regressor: dropout_regressor
  - model: mlp
  - logger: wandb
  - user: alex

# Number of objects to sample at the end of training
n_samples: 1024
# Random seeds
seed: 0
# Number of active learning iterations
al_n_rounds: 10
# Device
device: cuda
# Float precision
float_precision: 32

# Hydra config
hydra:
  # See: https://hydra.cc/docs/configure_hydra/workdir/
  run:
    dir: ${user.logdir.root}/${now:%Y-%m-%d_%H-%M-%S}
  job:
    # See: https://hydra.cc/docs/upgrades/1.1_to_1.2/changes_to_job_working_dir/
    # See: https://hydra.cc/docs/tutorials/basic/running_your_app/working_directory/#disable-changing-current-working-dir-to-jobs-output-dir
    chdir: True