defaults:
  - _self_
  - dataset: branin
  - oracle: branin
  - selector: selector
  - sampler: greedy
  - surrogate: gp
  - acquisition: botorch
  - user: default
  - logger: wandb

device: cpu
float_precision: 32
budget: 5
n_samples: 3
seed: 31415
maximize: False

# Hydra config
hydra:
  # See: https://hydra.cc/docs/configure_hydra/workdir/
  run:
    dir: ${user.logdir.root}/${now:%Y-%m-%d_%H-%M-%S_%f}
  sweep:
    dir: ${user.logdir.root}/multirun/${now:%Y-%m-%d_%H-%M-%S_%f}
  job:
    # See: https://hydra.cc/docs/upgrades/1.1_to_1.2/changes_to_job_working_dir/
    # See: https://hydra.cc/docs/tutorials/basic/running_your_app/working_directory/#disable-changing-current-working-dir-to-jobs-output-dir
    chdir: False
