defaults:
  - _self_ # with _self_ the overrides don't seem to work...
  - dataset: branin
  - env: grid
  - oracle: branin
  - sampler: random_gflownet #random_gflownet #greedy #gflownet #random
  - selector: score #selector #score
  - surrogate: gp 
  - acquisition: botorch_ucb #botorch_mve #botorch_ei #botorch_nei #botorch_ucb
  - user: default
  - logger: base
  - plotter: null #cime4r_branin # not working with gflownet because it produces new samples

device: cpu
float_precision: 32
budget: 10
n_samples: 5
seed: 31415
maximize: False


# Hydra config
hydra:
  # See: https://hydra.cc/docs/configure_hydra/workdir/
  run:
    dir: ${user.logdir.root}/${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: ${user.logdir.root}/multirun/${now:%Y-%m-%d_%H-%M-%S}
  job:
    # See: https://hydra.cc/docs/upgrades/1.1_to_1.2/changes_to_job_working_dir/
    # See: https://hydra.cc/docs/tutorials/basic/running_your_app/working_directory/#disable-changing-current-working-dir-to-jobs-output-dir
    chdir: False
