# @package _global_

defaults:
  # - _self_
  - env: amp
  - true_oracle: amp
  # last must be the best for project function to work as expected
  - oracle@_oracle_dict.1: amp_fid1
  - oracle@_oracle_dict.2: amp_fid2
  - oracle@_oracle_dict.3: amp
  - gflownet: trajectorybalance
  - user: nikita
  - proxy: mf_mes_proxy #mf_mes_proxy
  - dataset: dataset
  - regressor: dropout_regressor #dropout_regressor
  - model: regressive #mf_mlp #regressive
  - logger: wandb

# model:
#   shared_head: False

regressor:
  max_epochs: 2
  history: 1
  lr: 1e-3

proxy:
  cost_type: user
  candidate_set_path: null

logger:
  project_name: "Scratch"
  lightweight: False
  plot:
    period: 1000
    first_it: True
  test:
    period: 100
    n: 1000
  oracle:
    period: 1000
  # ckpts:
  #   policy:
  #     period: 1000
  do:
    times: False
    online: False
  tags:
    # - r(x) = (1000x)^8
    # - mf_mlp
    - tb
    - amp-mf-mes
    - backward_policy = shared
    - sampling_temp=1.0

env:
  proxy_state_format: ohe
  reward_func: power
  reward_beta: 1 #8
  length: 10
  reward_norm: 1e-3
  buffer:
    train:
      path: null
      # /home/mila/n/nikita.saxena/activelearning/storage/amp/data_train.csv
      n: null
      type: null
      seed: null
      output_csv: null 
    test:
      path: data_test.csv
      type: all
      output_pkl: buffer_data_test.csv
      n: null
      seed: null
      output_csv: null 
    

gflownet:
  active_learning: True
  sample_only: True
  random_action_prob: 0.001 #0.001
  optimizer:
    lr: 5e-4
    lr_z_mult: 20
    n_train_steps: 5
    batch_size: 32
  policy:
    forward:
      type: mlp
      n_hid: 2048
      n_layers: 2
      checkpoint: fp
    backward:
      type: uniform
      # shared_weights: True
  pct_offline: 0.0
  oracle:
    n: 500

dataset:
  n_samples: 30
  split: random #random
  train_fraction: 0.8
  dataloader:
    train:
      batch_size: 256
    test:
      batch_size: 256
  path:
    oracle_dataset:
      train: 
        path: /home/mila/n/nikita.saxena/activelearning/storage/amp/data_train.csv
        # TODO: Need to make this true before actual experiment
        get_scores: False
      test: 
        path: /home/mila/n/nikita.saxena/activelearning/storage/amp/data_test.csv
        get_scores: False
      # train: null
      # test: null
# Number of objects to sample at the end of training
# Sample 5*K and choose topK
n_samples: 5 #1024
# Random seeds
seed: 0
# Device
device: cuda
# Float precision
float_precision: 64
#It is strongly recommended to use double precision in BoTorch, as this improves both precision and stability and can help avoid numerical errors. See https://github.com/pytorch/botorch/discussions/1444
al_n_rounds: 15

multifidelity:
  proxy: True
  #  /home/mila/n/nikita.saxena/activelearning/storage/grid/nfid3_lower_quad.csv
  # /home/mila/n/nikita.saxena/activelearning/storage/grid/nfid3.csv
  # proxy_state_format: oracle
  fixed_cost: 1e-6
  rescale: 1

# Hydra config
hydra:
  # See: https://hydra.cc/docs/configure_hydra/workdir/
  run:
    dir: ${user.logdir.root}/${now:%Y-%m-%d_%H-%M-%S}
  job:
    # See: https://hydra.cc/docs/upgrades/1.1_to_1.2/changes_to_job_working_dir/
    # See: https://hydra.cc/docs/tutorials/basic/running_your_app/working_directory/#disable-changing-current-working-dir-to-jobs-output-dir
    chdir: True
