# @package _global_

defaults:
  # - _self_
  - env: grid
  - oracle@_oracle_dict.1: branin1 #branin1
  - oracle@_oracle_dict.2: branin2
  - oracle@_oracle_dict.3: branin3
  - gflownet: random
  - user: nikita
  - logger: wandb
  - dataset: dataset
  - regressor: mf_gp #mf_gp

logger:
  project_name: "RandomAgent" #Scratch RandomAgent
  test:
    period: 1
  oracle:
    period: 1
  do:
    times: False
    online: True
  plot:
    period: 1 #1000
    first_it: True
  tags:
    - branin
    - multi_fidelity

env:
  rescale: 10
  reward_func: power
  proxy_state_format: state
  length: 100
  reward_beta: 8.0
  reward_norm: 0.1
  buffer:
    train:
      path: null
      n: null
      seed: null
      output_csv: null 
    test:
      path: null
      type: all
      output_pkl: buffer_data_test.csv
      n: null
      seed: null
      output_csv: null 

dataset:
# TODO can we get rid of "do"
  fidelity: 
    do: True #add dependance on N_FID
    mixed: True
  n_samples: 30
  split: all_train #random
  dataloader:
    train:
      batch_size: null
    test:
      batch_size: null
  path:
    oracle_dataset: 
      train: 
        path: /home/mila/n/nikita.saxena/activelearning/storage/branin/nfid1_100x100.csv
        get_scores: True
      test: null

# Number of objects to sample at the end of training
# Sample 5*K and choose topK
n_samples: 30
# Random seeds
seed: 0
# Device
device: cuda
# Float precision
float_precision: 32
al_n_rounds: 30

multifidelity:
  toy: True
  rescale: 1
  proxy: True
  # candidate_set_path: /home/mila/n/nikita.saxena/activelearning/storage/branin/nfid3_100x100.csv

# Hydra config
hydra:
  # See: https://hydra.cc/docs/configure_hydra/workdir/
  run:
    dir: ${user.logdir.root}/${now:%Y-%m-%d_%H-%M-%S}
  job:
    # See: https://hydra.cc/docs/upgrades/1.1_to_1.2/changes_to_job_working_dir/
    # See: https://hydra.cc/docs/tutorials/basic/running_your_app/working_directory/#disable-changing-current-working-dir-to-jobs-output-dir
    chdir: True