defaults:
  # - _self_ # with _self_ the overrides don't seem to work...
  - dataset: ocp
  - oracle: ocp
  - selector: score
  - sampler: random
  - surrogate: svdkl_kernel_wrapper
  - acquisition: botorch_mve #botorch_mc
  - user: default
  - logger: wandb

dataset:
  checkpoint_path: /network/scratch/a/alexandre.duval/ocp/runs/4648581/checkpoints/best_checkpoint.pt

surrogate:
  mll_args: 
    num_data: 40593 # number of training data instances
  feature_extractor:
    n_input: 352
    n_output: 7
  train_epochs: 1
  lr: 0.1

device: cuda
float_precision: 32
budget: 1 # so far, we don't have an update strategy for ocp (i.e., we need to get data from some oracle and add it to the existing database)
n_samples: 20
seed: 31415
maximize: False

# Hydra config
hydra:
  # See: https://hydra.cc/docs/configure_hydra/workdir/
  run:
    dir: ${user.logdir.root}/${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: ${user.logdir.root}/multirun/${now:%Y-%m-%d_%H-%M-%S}
  job:
    # See: https://hydra.cc/docs/upgrades/1.1_to_1.2/changes_to_job_working_dir/
    # See: https://hydra.cc/docs/tutorials/basic/running_your_app/working_directory/#disable-changing-current-working-dir-to-jobs-output-dir
    chdir: False #True # need to have active learning directory for ocp config loading
