defaults:
  - main
  - override /dataset: hartmann
  - override /env: grid
  - override /oracle: hartmann

logger:
  do:
    online: False
    times: False
  project_name: test_logger
  run_name: ${env.length}_${sampler.id}_${surrogate.id}_${acquisition.id}
  # Log dir
  logdir:
    root: ./logs
    ckpts: ./ckpts
    overwrite: True
  debug: True
  progress: True
  tags: 
      - hartmann
      - al

dataset:
  train_path: ~/activelearning/data/hartmann/data_train.csv
  batch_size: 16
  
env:
  # Number of cells per dimension
  length: 10
  n_dim: 6
  # Mapping coordinates
  cell_min: -1
  cell_max: 1

device: cpu
float_precision: 32
budget: 10
n_samples: 5
seed: 31415
maximize: False
