defaults:
  - main
  - override /dataset: ocp
  - override /env: catalyst/hummingbird
  - override /oracle: ocp
  - override /surrogate: svdkl_kernel_wrapper 

surrogate:
  mll_args: 
    # number of training data instances
    num_data: 4059 #40593 
  feature_extractor:
    n_input: 352
    n_hidden: [265, 512, 265]
    n_output: 16
  train_epochs: 2 # 20
  lr: 0.01

logger:
  do:
    online: False
    times: False
  project_name: test_logger
  run_name: ${sampler.id}_${surrogate.id}_samples-${n_samples}_${acquisition.id}_${seed}
  # Log dir
  logdir:
    root: ./logs
    ckpts: ./ckpts
    overwrite: True
  debug: True
  progress: True
  tags: 
      - ocp
      - al

dataset:
  # checkpoint_path: /network/scratch/a/alexandre.duval/ocp/runs/4648581/checkpoints/best_checkpoint.pt
  checkpoint_path: /network/scratch/a/alexandre.duval/ocp/catalyst-ckpts/0.0.1/best_checkpoint.pt
  data_path: /network/scratch/a/alexandre.duval/ocp/runs/4657270/deup_dataset
  # we want to split the training set into 10% (train) and 90% (validation) for testing purposes
  train_fraction: 0.1


env:
  atomgraphconverter: 
    adsorbate_smiles: "*O"


device: cpu # cuda
float_precision: 64 # 32
budget: 10
n_samples: 100
seed: 98765
maximize: False

