defaults:
  # - _self_ # with _self_ the overrides don't seem to work...
  - dataset: ocp
  - oracle: ocp
  - sampler: random # greedy # random
  - selector: score # selector # score
  - surrogate: svdkl_kernel_wrapper
  - acquisition: botorch_mve #botorch_mve #botorch_ei #botorch_nei
  - user: default
  - logger: wandb

logger:
  project_name: test_ocp_training
  run_name: random_epochs-20_samples-100_mve_${seed}

dataset:
  checkpoint_path: /network/scratch/a/alexandre.duval/ocp/runs/4648581/checkpoints/best_checkpoint.pt
  data_path: /network/scratch/a/alexandre.duval/ocp/runs/4657270/deup_dataset
  # we want to split the training set into 10% (train) and 90% (validation) for testing purposes
  train_fraction: 0.1

surrogate:
  mll_args: 
    # number of training data instances
    num_data: 4059 #40593 
  feature_extractor:
    n_input: 352
    n_hidden: [265, 512, 265]
    n_output: 16
  train_epochs: 20
  lr: 0.01

device: cuda
float_precision: 64
budget: 10
n_samples: 100
seed: null
maximize: False

# Hydra config
hydra:
  # See: https://hydra.cc/docs/configure_hydra/workdir/
  run:
    dir: ${user.logdir.root}/${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: ${user.logdir.root}/multirun/${now:%Y-%m-%d_%H-%M-%S}
  job:
    # See: https://hydra.cc/docs/upgrades/1.1_to_1.2/changes_to_job_working_dir/
    # See: https://hydra.cc/docs/tutorials/basic/running_your_app/working_directory/#disable-changing-current-working-dir-to-jobs-output-dir
    # need to have active learning directory for ocp config loading
    chdir: False #True
