defaults:
  - test_ocp

surrogate:
  surrogate_mapper_cls: 
    _target_: activelearning.surrogate.surrogate_mapper.mapper.ConstantMapper
    _partial_: true

logger:
  do:
    online: False
    times: False
  project_name: test_logger
  run_name: ${sampler.id}_${surrogate.id}_samples-${n_samples}_${acquisition.id}_${seed}
  tags: 
      - ocp-const
      - al
