debug: 1
gflownet:
  adam_beta1: 0.9
  adam_beta2: 0.999
  batch_reward: 1
  bootstrap_tau: 0.0
  ckpt_period: 100
  clip_grad_norm: 0.0
  comet:
    project: gfn-grid
    skip: 0
    tags:
    - grid
    - dim2
    - length3
  device: cuda
  early_stopping: 0.0
  env_id: grid
  func: corners
  learning_rate: 0.001
  loss: tb
  lr_z_mult: 100
  max_step_len: 1
  mbsize: 16
  min_step_len: 1
  model_ckpt: gfn.pt
  momentum: 0.9
  n_hid: 128
  n_iter: 20000
  n_layers: 2
  num_empirical_loss: 200000
  opt: adam
  pct_batch_empirical: 0.0
  progress: 1
  temperature_logits: 1.0
  replay_capacity: 0
  reward_norm_std_mult: 8
  reward_beta: 8.0
  reward_func: power
  test:
    path: ~/scratch/datasets/grid/corners_d2l3_r0.csv
    period: 1
    score: energies
  oracle:
    nsamples: 100
    period: 1
    k:
      - 1
      - 10
  train_to_sample_ratio: 1
