# _target_: lambo.models.gp_models.SingleTaskSVGP
# max_shift: 0
# mask_size: 0
# bootstrap_ratio: null
# min_num_train: 128
# task_noise_init: 0.5
# lengthscale_init: 0.7
# gp_lr: 1e-3
# enc_lr: 1e-3
# bs: ${model.batch_size}
# eval_bs: 32
# num_epochs: 128
# holdout_ratio: 0.2
# early_stopping: True
# patience: 16
# eval_period: 2
# feature_dim: 16
# out_dim: 1
# num_inducing_points: 64
# learn_inducing_points: True
# encoder_wd: 1e-4
# mll_beta: 1e-2
# lengthscale_prior:
#   _target_: gpytorch.priors.NormalPrior
#   loc: ${surrogate.lengthscale_init}
#   scale: 1e-2
# noise_constraint:
#   _target_: gpytorch.constraints.GreaterThan
#   lower_bound: 1e-4