do:
  online: True
  times: True
ckpts:
  policy:
   # Period (number of iterations) of saving models
    period: 5000
  regressor:
    period: 10
# Train metrics
train:
  period: 1
# Test metrics
test:
  period: -1 
  n: 1 
  first_it: True
  kde:
    bandwidth: 0.1
    kernel: gaussian
# Oracle metrics
oracle:
  period: -1
  k:
    - 1
    - 10
    - 100
# Log dir
logdir:
  root: ./logs
  ckpts: ckpts
  data: data
  overwrite: True
lightweight: False 
progress: True
debug: False 
project_name: "MF-AL-GFN"
tags:
  - branin
  - sf