_target_: activelearning.acquisition.acquisition.BOTorchMonteCarloAcquisition

acq_fn_class: 
  _target_: botorch.acquisition.monte_carlo.qExpectedImprovement # qNoisyExpectedImprovement
  _partial_: true