_target_: activelearning.dataset.ocp.OCPDatasetHandler
checkpoint_path: /network/scratch/a/alexandre.duval/ocp/runs/4648581/checkpoints/best_checkpoint.pt
batch_size: 256
train_fraction: 1.0
shuffle: True
