task: amp
input_csv: data/amp.csv
output_dir: output
output_csv: data/amp.csv
output_filename: amp.pdf
data:
  methods:
   sfgfn:
     highlight: False
     dirname: "amp/gfn_sf"
     seeds:
       1:
         logdir: "2023-05-03_11-56-45"
   mf_random:
     highlight: False
     dirname: "amp/gfn_random"
     seeds:
       1:
         logdir: "2023-05-12_18-41-42"
       2:
         logdir: "2023-05-12_19-14-30"
       3:
         logdir: "2023-05-12_19-14-32"
   random_fid_gfn:
     highlight: False
     dirname: "amp/gfn_random_fid"
     seeds:
       1:
         logdir: "2023-05-10_22-15-42"
       2:
         logdir: "2023-05-12_20-08-56"
   mfppo:
     highlight: False
     dirname: "amp/ppo"
     seeds:
       1:
         logdir: "2023-05-13_17-49-20"
   mfgfn_linear:
     highlight: True
     dirname: "amp/gfn_linear_kernel"
     seeds:
       1:
         logdir: "2023-05-06_14-31-20"
   mfgfn_index:
     highlight: True
     dirname: "amp/gfn_index_kernel"
     seeds:
       1:
         logdir: "2023-05-01_23-18-47"
  higherbetter: True
  k:
    - 1
    - 10
    - 50
  batch_size_al: 32
  do_diversity: True
plot:
    x_axis:
        log: False

