task: branin
input_csv: data/branin.csv
output_dir: output
output_csv: data/branin.csv
output_filename: branin.pdf
do_methods:
    - sfgfn
    - random_fid_gfn
#     - mfbo
#     - mfppo
    - mfgfn
data:
  methods:
   sfgfn:
     highlight: False
     dirname: "branin/gfn_sf"
     seeds:
       1:
         logdir: "2023-05-06_18-52-02"
       2:
         logdir: "2023-05-08_16-59-06"
       3:
         logdir: "2023-05-08_17-08-04"
#      4:
#        logdir: "2023-05-03_06-35-40"
#      5:
#        logdir: "2023-05-03_06-32-45"
#      6:
#        logdir: "2023-05-03_18-49-33"
   mf_random:
     highlight: False
     dirname: "branin/gfn_random"
     seeds:
       1:
         logdir: "2023-05-12_18-59-13"
       2:
         logdir: "2023-05-12_18-59-22"
       3:
         logdir: "2023-05-12_18-59-27"
   random_fid_gfn:
     highlight: False
     dirname: "branin/gfn_random_fid"
     seeds:
       1:
         logdir: "2023-05-10_22-09-29"
       2:
         logdir: "2023-05-12_00-34-40"
       3:
         logdir: "2023-05-12_00-37-03"
   mfppo:
     highlight: False
     dirname: "branin/ppo"
     seeds:
       1:
         logdir: "2023-05-15_12-25-33"
   mfbo:
     highlight: False
     dirname: "branin/mfbo"
     seeds:
       1:
         logdir: ""
   mfgfn:
     highlight: True
     dirname: "branin/gfn_mf"
     seeds:
       1:
         logdir: "2023-05-04_22-24-48"
       2:
         logdir: "2023-05-03_06-41-16"
       3:
         logdir: "2023-05-03_06-41-50"
  higherbetter: False
  k:
    - 1
    - 10
    - 50
  batch_size_al: 30
  do_diversity: False
