output_dir: output
output_csv: branin.csv
output_filename: branin.pdf
data:
    methods:
       sf:
           1:
               logdir: "2023-05-03_06-35-40"
               run_path: "alexhg/Branin budget data set/p6nu2nzx"
           2:
               logdir: "2023-05-03_06-32-45"
               run_path: "alexhg/Branin budget data set/yvk5tox2"
           3:
               logdir: "2023-05-03_18-49-33"
               run_path: "alexhg/Branin budget data set/27japxej"
       mf:
           1:
               logdir: "2023-05-04_22-24-48"
               run_path: "alexhg/Branin budget data set/cijnbh4w"
           2:
               logdir: "2023-05-03_06-41-16"
               run_path: "alexhg/Branin budget data set/lwzlgxvj"
           3:
               logdir: "2023-05-03_06-41-50"
               run_path: "alexhg/Branin budget data set/g557nx3y"
    higherbetter: False
    k: 50
    batch_size_al: 30
    get_diversity: False
