task: dna
input_csv: data/cost_analysis.csv
output_dir: output
output_csv: data/cost_analysis.csv
output_filename: cost_analysis.pdf
do_methods:
    - sfgfn
    - mf_random
    - random_fid_gfn
    - mfppo
    - mfgfn
data:
  methods:
   sfgfn:
     highlight: False
     dirname: "dna/gfn_sf"
     seeds:
       1:
         logdir: "2023-05-06_11-38-43"
   mf_random:
     highlight: False
     dirname: "dna/gfn_random"
     seeds:
       1:
         logdir: "2023-05-12_19-17-41"
       2:
         logdir: "2023-05-12_19-23-46"
   random_fid_gfn:
     highlight: False
     dirname: "dna/gfn_random_fid"
     seeds:
       1:
         logdir: "2023-05-12_00-02-07"
       2:
         logdir: "2023-05-12_20-05-48"
   mfppo:
     highlight: False
     dirname: "dna/ppo"
     seeds:
       1:
         logdir: "2023-05-13_15-42-49"
   mfgfn_a:
     highlight: True
     dirname: "dna/gfn_linear_kernel"
     name: "MF-GFlowNet_A"
     seeds:
       1:
         logdir: "2023-05-06_04-35-33"
   mfgfn_b:
     highlight: True
     dirname: "dna/cost_ablation"
     name: "MF-GFlowNet_B"
     seeds:
       1:
         logdir: "2023-05-06_17-27-20"
   mfgfn_c:
     highlight: True
     dirname: "dna/cost_ablation"
     name: "MF-GFlowNet_C"
     seeds:
       1:
         logdir: "2023-05-08_16-55-59"
   mfgfn_d:
     highlight: True
     dirname: "dna/cost_ablation"
     name: "MF-GFlowNet_D"
     seeds:
       1:
         logdir: "2023-05-09_16-31-25"
  higherbetter: False
  k:
    - 1
    - 10
    - 100
  batch_size_al: 512
  do_diversity: True
plot:
    x_axis:
        log: False

