task: dna
input_csv: data/dna.csv
output_dir: output
output_csv: data/dna.csv
output_filename: dna.pdf
data:
  methods:
   sfgfn:
     highlight: False
     dirname: "dna/gfn_sf"
     seeds:
       1:
         logdir: "2023-05-06_11-38-43"
   mf_random:
     highlight: False
     dirname: "dna/gfn_random"
     seeds:
       1:
         logdir: "2023-05-12_19-17-41"
       2:
         logdir: "2023-05-12_19-23-46"
   random_fid_gfn:
     highlight: False
     dirname: "dna/gfn_random_fid"
     seeds:
       1:
         logdir: "2023-05-12_00-02-07"
       2:
         logdir: "2023-05-12_20-05-48"
   mfppo:
     highlight: False
     dirname: "dna/ppo"
     seeds:
       1:
         logdir: "2023-05-13_15-42-49"
   mfgfn:
     highlight: True
     dirname: "dna/gfn_linear_kernel"
     name: "MF-GFlowNet"
     seeds:
       1:
         logdir: "2023-05-06_04-35-33"
#    mf_linear:
#      highlight: True
#      dirname: "dna/gfn_linear_kernel"
#      seeds:
#        1:
#          logdir: "2023-05-06_04-35-33"
#    mf_index:
#      highlight: True
#      dirname: "dna/gfn_index_kernel"
#      seeds:
#        1:
#          logdir: "2023-05-05_14-26-31"
  higherbetter: False
  k:
    - 1
    - 10
    - 100
  batch_size_al: 512
  do_diversity: True
plot:
    x_axis:
        log: False

