task: hartmann
input_csv: data/hartmann.csv
output_dir: output
output_csv: data/hartmann.csv
output_filename: hartmann.pdf
data:
  methods:
   sf:
     dirname: "hartmann/gfn_sf"
     name: "Single-fidelity (highest) AL"
     seeds:
       1:
         logdir: "2023-05-05_01-08-33"
       2:
         logdir: "2023-05-04_06-27-13"
       3:
         logdir: "2023-05-04_06-27-13"
   mf:
     dirname: "hartmann/gfn_mf"
     name: "Multi-fidelity AL"
     seeds:
       1:
         logdir: "2023-05-05_10-51-53"
       2:
         logdir: "2023-05-04_06-27-11"
       3:
         logdir: "2023-05-04_06-27-12"
  higherbetter: True
  k:
    - 1
    - 10
  batch_size_al: 10
  do_diversity: False
