task: molecules
input_csv: data/molecules_ea.csv
output_dir: output
output_csv: data/molecules_ea.csv
output_filename: molecules_ea.pdf
do_methods:
    - sfgfn
    - mf_random
    - random_fid_gfn
    - mfppo
    - mfgfn
data:
  methods:
   sfgfn:
     highlight: False
     dirname: "molecules_ea/gfn_sf"
     seeds:
       1:
         logdir: "2023-05-11_20-52-24"
       2:
         logdir: "2023-07-18_04-45-24"
       3:
         logdir: "2023-07-18_04-47-34"
   mf_random:
     highlight: False
     dirname: "molecules_ea/gfn_random"
     seeds:
       1:
         logdir: "2023-05-12_18-28-50"
       2:
         logdir: "2023-05-12_18-28-50"
       3:
         logdir: "2023-05-13_05-36-10"
   random_fid_gfn:
     highlight: False
     dirname: "molecules_ea/gfn_random_fid"
     seeds:
       1:
         logdir: "2023-05-12_20-17-51"
       2:
         logdir: "2023-07-18_04-22-29"
       3:
         logdir: "2023-07-18_04-24-51"
   mfppo:
     highlight: False
     dirname: "molecules_ea/ppo"
     seeds:
       1:
         logdir: "2023-05-14_15-56-25"
       2:
         logdir: "2023-07-18_07-11-29"
       3:
         logdir: "2023-07-27_04-30-58"
   mfgfn:
     highlight: True
     dirname: "molecules_ea/gfn_mf"
     name: "MF-GFlowNet"
     seeds:
       1:
         logdir: "2023-05-12_01-42-34"
       2:
         logdir: "2023-07-18_05-31-26"
       3:
         logdir: "2023-07-27_04-51-58"
  higherbetter: True
  k:
    - 1
    - 10
    - 50
    - 100
    - 200
  k_plot: 100
  batch_size_al: 128
  do_diversity: True
  do_topk_diverse: True
plot:
    x_axis:
        log: False

