task: molecules
input_csv: data/molecules_ip.csv
output_dir: output
output_csv: data/molecules_ip.csv
output_filename: molecules_ip.pdf
do_methods:
    - sfgfn
    - mf_random
    - random_fid_gfn
    - mfppo
    - mfgfn
data:
  methods:
   sfgfn:
     highlight: False
     dirname: "molecules_ip/gfn_sf"
     seeds:
       1:
         logdir: "2023-05-11_20-52-32"
   sfgfn_cost1:
     highlight: False
     dirname: "molecules_ip/gfn_sf_cost1"
     seeds:
       1:
         logdir: "2023-08-03_04-00-17"
       2:
         logdir: "2023-08-03_04-55-01"
       3:
         logdir: "2023-08-03_05-13-55"
   sfgfn_b256:
     highlight: False
     dirname: "molecules_ip/batch_ablation/b256/sf"
     seeds:
       1:
         logdir: "2023-08-05_14-32-48"
       2:
         logdir: "2023-08-05_14-42-01"
   sfgfn_b64:
     highlight: False
     dirname: "molecules_ip/batch_ablation/b64/sf"
     seeds:
       1:
         logdir: "2023-08-05_14-32-07"
       2:
         logdir: "2023-08-05_14-43-06"
   mf_random:
     highlight: False
     dirname: "molecules_ip/gfn_random"
     seeds:
       1:
         logdir: "2023-05-12_19-41-52"
       2:
         logdir: "2023-05-12_19-59-50"
       3:
         logdir: "2023-05-12_19-59-53"
   random_fid_gfn:
     highlight: False
     dirname: "molecules_ip/gfn_random_fid"
     seeds:
       1:
         logdir: "2023-05-13_19-58-14"
   mfppo:
     highlight: False
     dirname: "molecules_ip/ppo"
     seeds:
       1:
         logdir: "2023-05-14_15-55-42"
   mfgfn:
     highlight: True
     dirname: "molecules_ip/gfn_mf"
     seeds:
       1:
         logdir: "2023-05-12_07-18-46"
   mfgfn_b256:
     highlight: False
     dirname: "molecules_ip/batch_ablation/b256/mf"
     seeds:
       1:
         logdir: "2023-08-04_01-40-29"
       2:
         logdir: "2023-08-04_02-33-42"
       3:
         logdir: "2023-08-04_03-39-45"
   mfgfn_b64:
     highlight: False
     dirname: "molecules_ip/batch_ablation/b64/mf"
     seeds:
       1:
         logdir: "2023-08-04_01-39-35"
       2:
         logdir: "2023-08-04_02-39-43"
       3:
         logdir: "2023-08-04_03-06-40"
  higherbetter: False
  k:
    - 1
    - 10
    - 50
    - 100
    - 200
  k_plot: 100
  batch_size_al: 128
  do_diversity: True
  do_topk_diverse: True
plot:
    x_axis:
        log: False

