task: molecules_ea
input_csv: data/molecules_ea.csv
output_dir: output
output_csv: data/molecules_ea.csv
output_filename: molecules_ea.pdf
data:
  methods:
   sfgfn:
     highlight: False
     dirname: "molecules_ea/gfn_sf"
     seeds:
       1:
         logdir: "2023-05-11_20-52-24"
   mf_random:
     highlight: False
     dirname: "molecules_ea/gfn_random"
     seeds:
       1:
         logdir: "2023-05-12_18-28-50"
       2:
         logdir: "2023-05-12_18-28-50"
       3:
         logdir: "2023-05-13_05-36-10"
  higherbetter: True
  k:
    - 1
    - 10
    - 100
  batch_size_al: 128
  do_diversity: False
plot:
    x_axis:
        log: False

