task: molecules
input_csv: data/molecules_ea.csv
output_dir: output
output_csv: data/molecules_ea.csv
output_filename: molecules_ea.pdf
do_methods:
    - sfgfn
    - mf_random
    - random_fid_gfn
    - mfppo
    - mfgfn
data:
  methods:
   sfgfn:
     highlight: False
     dirname: "molecules_ea/gfn_sf"
     seeds:
       1:
         logdir: "2023-05-11_20-52-24"
   mf_random:
     highlight: False
     dirname: "molecules_ea/gfn_random"
     seeds:
       1:
         logdir: "2023-05-12_18-28-50"
       2:
         logdir: "2023-05-12_18-28-50"
       3:
         logdir: "2023-05-13_05-36-10"
   random_fid_gfn:
     highlight: False
     dirname: "molecules_ea/gfn_random_fid"
     seeds:
       1:
         logdir: "2023-05-12_20-17-51"
   mfppo:
     highlight: False
     dirname: "molecules_ea/ppo"
     seeds:
       1:
         logdir: "2023-05-14_15-56-25"
   mfgfn:
     highlight: True
     dirname: "molecules_ea/gfn_mf"
     name: "MF-GFlowNet"
     seeds:
       1:
         logdir: "2023-05-12_01-42-34"
  higherbetter: True
  k:
    - 1
    - 10
    - 100
  batch_size_al: 128
  do_diversity: True
plot:
    x_axis:
        log: False

