_target_: activelearning.sampler.sampler.GFlowNetSampler

defaults:
  - gflownet: base
  - policy: mlp_trajectorybalance
  - proxy: acquisition
  - logger: base
  - evaluator: base
  - buffer: base

id: gflownet
