_target_: activelearning.logger.Logger

do:
  online: False
  times: False
ckpts:
  policy:
   # Period (number of iterations) of saving models
    period: 5000
  regressor:
    period: 10
# Train metrics
train:
  period: 1
# Test metrics
test:
  first_it: True
  period: 100
  n: 100
  kde:
    bandwidth: 0.1
    kernel: gaussian
# Oracle metrics
oracle:
  period: 100000
  k:
    - 1
    - 10
    - 100
# Log dir
logdir:
  root: ./logs
  ckpts: ckpts
  data: data
  overwrite: True
lightweight: False 
progress: True
debug: False
