_target_: activelearning.utils.logger.ActiveLearningLogger

surrogate_ckpts: surrogate

do:
  online: False
  times: False

project_name: "ActiveLearning"

# Log dir
logdir:
  root: ./logs
  ckpts: ckpts
  overwrite: True
debug: False
lightweight: False
progress: True
context: "0"
notes: null # wandb run notes (e.g. "baseline")
entity: null # wandb entity (e.g. "gflownet", "hernanga", "mila-ocp" etc.)
